# SCRIPT: snp_panel_gtex_expression_analysis.R
# AUTHOR: Aitor Almanza
# DATE: 31/03/2026
# REPOSITORY: https://github.com/xaitorx/44-SNP-barcode-for-robust-sample-tracking-in-research-and-clinical-settings-
# WARNINGS:
#   - Hardcoded paths
#   - Large data: GTEx files are large
#   - Runtime: Merging multiple tissue files may take 10-30 minutes.
#   - This script assumes Table 1 (`table_1`) was generated by a previous script.

# ---- 0. LOAD LIBRARIES ----
library(data.table)
library(stringr)
library(pheatmap)
library(circlize)
library(ComplexHeatmap)
library(Polychrome)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)

# ---- 1. LOAD & PREPARE SNP PANEL DATA ----
# Load final SNP panel table (adjust path to your local setup)
SNP_panel_table <- read.csv2("data/SNP_panel_final.txt")

# Exclude SNPs that failed validation or annotation
snps_fail <- c("rs5997988", "rs5997435", "rs2032653")
genes_fail <- c("EIF4ENIF1", "ZNRF3", "UTY")  # Reserved for logging/debugging
SNP_panel_table <- SNP_panel_table[!(SNP_panel_table$rs_id %in% snps_fail), ]

# ---- 2. LOAD GTEx GENE EXPRESSION DATA ----
# Source: GTEx Portal v10 (https://gtexportal.org/home/datasets)
source_gtex <- "../path/to/GTEx/"  # ⚠️ UPDATE PATH

# Process each tissue file (GCT format)
# Calculate mean TPM across samples and percentile rank per tissue
list_expr_tissue <- list()
gtex_files <- list.files(source_gtex, pattern = "\\.gct\\.gz$", full.names = TRUE)
message("📂 Found ", length(gtex_files), " GTEx tissue files")

for (i in gtex_files) {
  temp_tissue <- fread(i)
  temp_tissue1 <- cbind(temp_tissue[,1:2],rowMeans(temp_tissue[,3:ncol(temp_tissue)]))
  temp_tissue1$percentile <- ecdf(temp_tissue1$V2)(temp_tissue1$V2)
  colnames(temp_tissue1)[4] <- str_extract(i, "(?<=gene_tpm_v10_).*(?=\\.gct\\.gz)")
  print(str_extract(i, "(?<=gene_tpm_v10_).*(?=\\.gct\\.gz)"))
  list_expr_tissue[[i]] <- temp_tissue1[,c(1:2,4)]
}

# Merge all tissues into single matrix
GTEX_completo <- Reduce(function(dtf1,dtf2) merge(dtf1,dtf2,by=c("Name","Description")), list_expr_tissue)

# ---- 3. INTERSECT with panel genes ----
lista_completa <- list()
for (i in 1:length(SNP_panel_table$rs_id)) {
  genes <- trimws(unlist(strsplit(SNP_panel_table$ENSEMBL_ID[i], "\\|")))
  for (z in genes) {
    if (z == "") { next }
    gene_tissue_temp <- cbind(rs_id = SNP_panel_table$rs_id[i] ,GTEX_completo[grepl(z,GTEX_completo$Name,fixed = TRUE),])
    lista_completa[[paste(i,z,sep="_")]] <- gene_tissue_temp
  }
  print(i)
}

#
GTEX_panel <- as.data.frame(do.call("rbind", lista_completa))
GTEX_panel <- GTEX_panel[!is.na(GTEX_panel$Description),]

# ---- 4. AGGREGATE per SNP ? ----
GTEX_panel_aggregated <- aggregate(.~ rs_id, GTEX_panel[,c(1,4:ncol(GTEX_panel))], mean, na.rm = TRUE)
GTEX_panel_IDs <- aggregate(.~ rs_id, GTEX_panel[,1:3], paste, collapse="/")

# combine
GTEX_panel_final <- merge(GTEX_panel_IDs, GTEX_panel_aggregated, by=1)
GTEX_final_plot <- GTEX_panel_final[,4:ncol(GTEX_panel_final)]
row.names(GTEX_final_plot) <- GTEX_panel_final$rs_id

# reorder
GTEX_panel_final <- GTEX_panel_final[match(table_1$rs_id, GTEX_panel_final$rs_id),]

# save table
write.table(GTEX_panel_final , file = "tables/GTEX_SNP_final.txt", row.names = FALSE)

# ---- 5. PLOT heatmap ----
col_fun = colorRamp2(c(0,50, 100), c("blue","white", "red"))

# Plot
# Generate colors and name them by tissue
coroles <- glasbey.colors(n = length(unique(gsub("_.*", "", colnames(GTEX_final_plot)))))
names(coroles) <- unique(gsub("_.*", "", colnames(GTEX_final_plot)))

# Create annotation data frame (MUST have column name, e.g., "tissue")
anno_df <- data.frame(Tissue = gsub("_.*", "", colnames(GTEX_final_plot)), row.names = colnames(GTEX_final_plot))

# Define color mapping: list(column_name = named_color_vector)
col_mapping <- list(Tissue = coroles)  

# Create annotation
annotations_tissue <- HeatmapAnnotation(
  df = anno_df,
  col = col_mapping,
  which = "col"
)

#
ht = Heatmap(as.matrix(GTEX_final_plot) * 100, 
             col = col_fun,
             name = "Percentile", 
             rect_gp = gpar(col = "white", lwd = 1),
             top_annotation=annotations_tissue,
             column_names_gp = grid::gpar(fontsize = 11),
             row_names_gp = grid::gpar(fontsize = 10),
             column_names_rot = 45) 
ht1 = draw(ht, padding = unit(c(2, 50, 2, 2), "mm")) ## see right heatmap in following

#
pdf("plots/gtex_expression_heatmap.pdf", width = 14, height = 10)
draw(ht1)
dev.off()

#
# ---- 6. CMRP per tissue ----
GTEX_short <- (GTEX_panel_final[,4:57] > 0.75)
sort(colSums(GTEX_short), decreasing = TRUE)
row.names(GTEX_short) <- GTEX_panel_final$rs_id

# load eMP metrics
probs <- read.delim("tables/table_2.tsv")

list_crmps <- list()
list_n_snps <- list()
for (i in 1:ncol(GTEX_short)) {
  valid_snps <- probs[probs$rs_id %in% names(GTEX_short[GTEX_short[,i] == TRUE,i]),]
  crmp_temp <- apply(valid_snps[,8:13], 2, prod)
  list_crmps[[colnames(GTEX_short)[i]]] <- crmp_temp
  list_n_snps[[colnames(GTEX_short)[i]]] <- nrow(valid_snps)
}

tissue_crmps <- as.data.frame(do.call("rbind", list_crmps))
tissue_snps <- as.data.frame(do.call("rbind", list_n_snps))

# melt
tissue_crmps_melted <- melt(as.matrix(tissue_crmps))
tissue_snps_melted <- melt(as.matrix(tissue_snps))

# combine
tissue_todo_melted <- merge(tissue_crmps_melted, tissue_snps_melted[,c(1,3)], by.x="Var1",by.y="Var1")
tissue_todo_melted <- tissue_todo_melted[order(tissue_todo_melted$value.y, decreasing = TRUE),]
tissue_todo_melted$Var1 <- factor(tissue_todo_melted$Var1, levels = unique(tissue_todo_melted$Var1))
tissue_todo_melted$value.y <- as.numeric(tissue_todo_melted$value.y)
tissue_todo_melted$log <- -log10(tissue_todo_melted$value.x)
tissue_todo_melted$group <- gsub("_.*", "",tissue_todo_melted$Var1)

### plot things
crmp_plot <- ggplot(tissue_todo_melted, aes(x=Var1, color=Var2)) +
  geom_point( aes(y=value.y), size=2, color="black") + 
  geom_line( aes(y=log*3, group=Var2), size=2, alpha=0.5) +
  scale_y_continuous(
    # Features of the first axis
    name = "n SNPs > 75th percentile",
    # Add a second axis and specify its features
    sec.axis = sec_axis(trans=~./3, name="-log10(CRMP)")
  ) + theme_minimal() + labs(x="") +
  theme(axis.text.x = element_text(angle = 45, hjust=1,size = 11,color="black"),
        plot.margin = margin(t = 10, r = 10, b = 50, l = 50, unit = "pt")) +
  geom_hline(yintercept = 18, linetype = "dashed", color = "red", linewidth = 1) +
  scale_color_manual(values = c("eMP_AFR"="#E41A1C","eMP_EUR"="#377EB8","eMP_SA"="#4DAF4A", "eMP_EA"="#984EA3", "eMP_LATAM"="#FF7F00")) 


### create figure panel
crmp_plot <- crmp_plot + theme(plot.margin=unit(c(2, 2, 2, 5), "cm"))
gb1 <- grid.grabExpr(draw(ht1)) # converts the complexheatmap into grob
p <- plot_grid(gb1, crmp_plot, nrow=2,rel_heights = c(3, 1.5), labels="AUTO", label_size =30)

#
pdf("plots/cmrp_tissue.pdf", width = 14, height = 15)
print(p)
dev.off()


### Tabla discusion
tabla_discusion <- read.delim("data/Pros_Cons.txt", sep=" ")

mytheme <- ttheme_default(core = list(fg_params = list(hjust=0, x=0.05, 
                                                       fontsize=12)),
                          colhead = list(fg_params = list(fontsize=13, 
                                                          fontface="bold"))
)
g1 <- tableGrob(tabla_discusion, theme = mytheme, rows=NULL)
grid.newpage()

pdf("tables/pros_cons.pdf", width = 14, height = 15)
grid.draw(g1)
dev.off()




